# fly.toml — конфигурация для maxkorzhpaymentbot
app = "maxkorzhpaymentbot"
primary_region = "waw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port         = 8080
  force_https           = true
  auto_start_machines   = true
  min_machines_running  = 1
  processes             = ["app"]
